# Generated by Django 3.2.6 on 2021-08-28 15:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('director_name', models.CharField(max_length=50)),
                ('budget', models.BigIntegerField()),
                ('box_office', models.BigIntegerField()),
                ('imdb_ratings', models.FloatField()),
                ('release_date', models.DateField(default=django.utils.timezone.now)),
                ('verdict', models.CharField(max_length=50)),
                ('poster', models.ImageField(default=' ', upload_to='movie\\images')),
            ],
        ),
    ]
